Reproduce the whole app using React
AWIXOR/1337-contributors pull request #33
Opened 2022-04-05 11:46 UTC by abellaismail7

this pull request is related #24.

here is the result:
https://1337-contributors-one.vercel.app/

2022-04-05 14:32 UTC, AWIXOR requested changes
Can you please change `0.0.0.0` to `localhost` in `package.json`

2022-04-05 14:47 UTC, abellaismail7 commented on package.json
> +    "start": "cross-env NODE_ENV=development webpack serve --config tools/webpack/webpack.config.dev.js --host 0.0.0.0 --port 8000",
with 0.0.0.0 the website will be available in the network is that a problem?

2022-04-05 14:58 UTC, AWIXOR commented on package.json
> +    "start": "cross-env NODE_ENV=development webpack serve --config tools/webpack/webpack.config.dev.js --host 0.0.0.0 --port 8000",
`0.0.0.0` didn't work for me and I believe it will not work for many others, so just use `127.0.0.1` or `localhost`

2022-04-06 08:59 UTC, abellaismail7 commented on package.json
> +    "start": "cross-env NODE_ENV=development webpack serve --config tools/webpack/webpack.config.dev.js --host 0.0.0.0 --port 8000",
done

2022-04-06 12:02 UTC, AWIXOR approved these changes

2022-04-06 12:03 UTC, AWIXOR commented on package.json
> +    "start": "cross-env NODE_ENV=development webpack serve --config tools/webpack/webpack.config.dev.js --host 0.0.0.0 --port 8000",
Great, thank you!

2022-04-06 12:03 UTC, merged